[package]
name = "xremap"
version = "0.8.6"
edition = "2021"
description = "Dynamic key remapp for X and Wayland"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstyle = "1.0.1"
anyhow = "1.0.72"
clap = { version = "4.3.19", features = ["derive", "unstable-styles"] }
clap_complete = "4.3.2"
derive-where = "1.2.1"
env_logger = "0.10.0"
evdev = "0.12.1"
fork = "0.1"
indoc = "2.0"
lazy_static = "1.4.0"
log = "0.4.19"
nix = "0.26.2"
regex = "1.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "2.3", features = ["chrono"] }
serde_yaml = "0.9"
swayipc = { version = "3.0.1", optional = true }
x11rb = { version = "0.12.0", optional = true }
zbus = { version = "1.9.2", optional = true }
hyprland = { version = "0.3.4", optional = true }

[features]
gnome = ["zbus"]
sway = ["swayipc"]
x11 = ["x11rb"]
hypr = ["hyprland"]
kde = ["zbus"]
